import * as fs from 'fs';
import * as xml2js from 'xml2js';
import { DisqusData, DisqusThread, DisqusPost, WxrOptions } from './types';

export async function convertDisqusToWxr(
  inputFile: string,
  outputFile: string,
  options: WxrOptions
): Promise<void> {
  const xmlContent = fs.readFileSync(inputFile, 'utf-8');
  const parser = new xml2js.Parser();
  const disqusData: DisqusData = await parser.parseStringPromise(xmlContent);

  const threads = disqusData.disqus.thread || [];
  const posts = disqusData.disqus.post || [];

  // Filter out deleted and spam posts
  const validPosts = posts.filter(post => {
    const isDeleted = post.isDeleted?.[0] === 'true';
    const isSpam = post.isSpam?.[0] === 'true';
    return !isDeleted && !isSpam;
  });

  // Group posts by thread
  const postsByThread = new Map<string, DisqusPost[]>();
  validPosts.forEach(post => {
    const threadId = post.thread?.[0]?.$?.['dsq:id'];
    if (threadId) {
      if (!postsByThread.has(threadId)) {
        postsByThread.set(threadId, []);
      }
      postsByThread.get(threadId)!.push(post);
    }
  });

  const wxrContent = generateWxr(threads, postsByThread, options);
  fs.writeFileSync(outputFile, wxrContent, 'utf-8');
}

function generateWxr(
  threads: DisqusThread[],
  postsByThread: Map<string, DisqusPost[]>,
  options: WxrOptions
): string {
  const now = new Date().toUTCString();
  
  let wxr = `<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a WordPress eXtended RSS file generated by disqus-to-wxr converter. -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.0/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.0/"
>
    <channel>
        <title>${escapeXml(options.title)}</title>
        <link>${escapeXml(options.url)}</link>
        <description>${escapeXml(options.description)}</description>
        <pubDate>${now}</pubDate>
        <language>en</language>
        <wp:wxr_version>1.0</wp:wxr_version>
        <wp:base_site_url>${escapeXml(options.url)}</wp:base_site_url>
        <wp:base_blog_url>${escapeXml(options.url)}</wp:base_blog_url>
`;

  threads.forEach((thread, index) => {
    const threadId = thread.$['dsq:id'];
    const comments = postsByThread.get(threadId) || [];
    
    if (comments.length === 0) return; // Skip threads without comments

    const link = thread.link?.[0] || '';
    const title = thread.title?.[0] || 'Untitled';
    const createdAt = thread.createdAt?.[0] || new Date().toISOString();
    const author = thread.author?.[0]?.username?.[0] || 'admin';
    
    const postId = index + 1;
    const pubDate = formatDate(createdAt);
    const postDate = formatDateForWp(createdAt);

    wxr += `
        <item>
            <title>${escapeXml(title)}</title>
            <link>${escapeXml(link)}</link>
            <pubDate>${pubDate}</pubDate>
            <dc:creator><![CDATA[${author}]]></dc:creator>
            <guid isPermaLink="false">${escapeXml(link)}</guid>
            <description></description>
            <content:encoded><![CDATA[]]></content:encoded>
            <excerpt:encoded><![CDATA[]]></excerpt:encoded>
            <wp:post_id>${postId}</wp:post_id>
            <wp:post_date>${postDate}</wp:post_date>
            <wp:post_date_gmt>${postDate}</wp:post_date_gmt>
            <wp:comment_status>open</wp:comment_status>
            <wp:ping_status>open</wp:ping_status>
            <wp:post_name>${generateSlug(title)}</wp:post_name>
            <wp:status>publish</wp:status>
            <wp:post_parent>0</wp:post_parent>
            <wp:menu_order>0</wp:menu_order>
            <wp:post_type>post</wp:post_type>
            <wp:post_password></wp:post_password>
            <wp:is_sticky>0</wp:is_sticky>
`;

    // Create mapping from Disqus post ID to WordPress comment ID
    const disqusToWpCommentId = new Map<string, number>();
    comments.forEach((comment, commentIndex) => {
      const disqusPostId = comment.$['dsq:id'];
      disqusToWpCommentId.set(disqusPostId, commentIndex + 1);
    });

    // Add comments
    comments.forEach((comment, commentIndex) => {
      wxr += generateComment(comment, commentIndex + 1, disqusToWpCommentId);
    });

    wxr += `        </item>
`;
  });

  wxr += `    </channel>
</rss>`;

  return wxr;
}

function generateComment(
  post: DisqusPost,
  commentId: number,
  disqusToWpCommentId: Map<string, number>
): string {
  const postId = post.$['dsq:id'];
  const message = post.message?.[0] || '';
  const createdAt = post.createdAt?.[0] || new Date().toISOString();
  const author = post.author?.[0];
  const authorName = author?.name?.[0] || 'Anonymous';
  const authorUsername = author?.username?.[0] || '';
  const parentDisqusId = post.parent?.[0]?.$?.['dsq:id'];
  
  // Map Disqus parent ID to WordPress comment ID
  const parentId = parentDisqusId ? (disqusToWpCommentId.get(parentDisqusId) || 0) : 0;
  
  const commentDate = formatDateForWp(createdAt);

  return `            <wp:comment>
                <wp:comment_id>${commentId}</wp:comment_id>
                <wp:comment_author><![CDATA[${authorName}]]></wp:comment_author>
                <wp:comment_author_email></wp:comment_author_email>
                <wp:comment_author_url></wp:comment_author_url>
                <wp:comment_author_IP></wp:comment_author_IP>
                <wp:comment_date>${commentDate}</wp:comment_date>
                <wp:comment_date_gmt>${commentDate}</wp:comment_date_gmt>
                <wp:comment_content><![CDATA[${message}]]></wp:comment_content>
                <wp:comment_approved>1</wp:comment_approved>
                <wp:comment_type></wp:comment_type>
                <wp:comment_parent>${parentId}</wp:comment_parent>
                <wp:comment_user_id>0</wp:comment_user_id>
            </wp:comment>
`;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function formatDate(isoDate: string): string {
  return new Date(isoDate).toUTCString();
}

function formatDateForWp(isoDate: string): string {
  const date = new Date(isoDate);
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, '0');
  const day = String(date.getUTCDate()).padStart(2, '0');
  const hours = String(date.getUTCHours()).padStart(2, '0');
  const minutes = String(date.getUTCMinutes()).padStart(2, '0');
  const seconds = String(date.getUTCSeconds()).padStart(2, '0');
  
  return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
}

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
